# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Puu-NwRUnzZUw6qCrozm-oJqXQdyg6h
"""

print ('Dia berkata: "Pergilah dari sini!" ')

print("Aku menimpali: \"Apakah kau ingin aku 'angkat kaki' dari sini!?\"")