# -*- coding: utf-8 -*-
"""Manipulasi String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1107eTS_jiYiMqDY5OFv8gXWzr4Ql0n9S
"""

nama = "Azizun Hakim"
asal = "Indonesia"

print(nama)

print(asal)

"""Manipulasi String"""

print(nama, asal)

print("halo, nama saya",nama)

print("halo, nama saya",nama, "asal saya dari",asal)

print (nama, asal)

data_lengkap = nama + asal

print(data_lengkap)

"""String + Non String"""

asal_kota = "Bandar Lampung"
kode_pos = 35111

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print(asal_kota_x3)

